management:
    endpoint:
        health:
            show-details: never

aws:
    region: ${AWS_REGION}
    sqs:
        queue-url: ${AWS_SQS_QUEUE_URL}

kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    schema-registry-url: ${KAFKA_SCHEMA_REGISTRY_URL}
    topic: ${KAFKA_TOPIC:eventos-autorizacao}
