{
  "type": "record",
  "name": "EventoAutorizacao",
  "namespace": "br.com.srportto.eventos.autorizacao",
  "doc": "Espelho da linha da tabela autorizacoes, publicada no topico eventos-autorizacao.",
  "fields": [
    { "name": "id_autorizacao", "type": { "type": "string", "logicalType": "uuid" } },
    { "name": "id_particao_conta", "type": "int" },
    { "name": "data_fim_vigencia", "type": { "type": "int", "logicalType": "date" } },
    { "name": "tipo_produto", "type": "long" },
    { "name": "status", "type": "int" },
    { "name": "motivo_status", "type": ["null", "string"], "default": null },
    { "name": "data_inicio_vigencia", "type": ["null", { "type": "int", "logicalType": "date" }], "default": null },
    { "name": "data_hora_inclusao", "type": { "type": "long", "logicalType": "local-timestamp-micros" } },
    { "name": "data_hora_ultima_atlz", "type": { "type": "long", "logicalType": "local-timestamp-micros" } },
    { "name": "valor", "type": ["null", { "type": "bytes", "logicalType": "decimal", "precision": 17, "scale": 2 }], "default": null },
    { "name": "id_autorizacao_empresa", "type": ["null", "string"], "default": null },
    { "name": "valor_limite", "type": ["null", { "type": "bytes", "logicalType": "decimal", "precision": 17, "scale": 2 }], "default": null },
    { "name": "frequencia", "type": ["null", "int"], "default": null },
    { "name": "quantidade_dividas_ciclo", "type": ["null", "int"], "default": null },
    { "name": "indicador_uso_limite_conta", "type": ["null", "int"], "default": null },
    { "name": "indicador_tipo_mensageria", "type": ["null", "int"], "default": null },
    { "name": "codigo_canal_contratacao", "type": "string" },
    { "name": "descricao", "type": ["null", "string"], "default": null },
    { "name": "id_unico_conta_contratante", "type": ["null", { "type": "string", "logicalType": "uuid" }], "default": null },
    { "name": "id_pessoa_pagadora", "type": ["null", { "type": "string", "logicalType": "uuid" }], "default": null },
    { "name": "id_pessoa_devedora", "type": ["null", { "type": "string", "logicalType": "uuid" }], "default": null },
    { "name": "id_pessoa_recebedora", "type": ["null", { "type": "string", "logicalType": "uuid" }], "default": null },
    { "name": "codigo_canal_cancelamento", "type": ["null", "string"], "default": null },
    { "name": "id_pessoa_cancelamento", "type": ["null", { "type": "string", "logicalType": "uuid" }], "default": null },
    { "name": "data_hora_cancelamento", "type": ["null", { "type": "long", "logicalType": "local-timestamp-micros" }], "default": null },
    { "name": "motivo_cancelamento", "type": ["null", "string"], "default": null },
    { "name": "metadados", "type": ["null", "string"], "default": null }
  ]
}
