management:
    endpoint:
        health:
            show-details: always

aws:
    endpoint: http://localhost:4566
    region: us-east-1
    access-key: test
    secret-key: test
    sns:
        topic-arn: arn:aws:sns:us-east-1:000000000000:sns-estados-autorizacao
